version: "3.9"
services:
  nodejs:
    image: node:20.12.1
    working_dir: /usr/src/app
    ports:
      - "${NODE_PORT}:3000"
    expose:
      - ${NODE_PORT}
    depends_on:
      - mysql
    volumes:
      - ".:/usr/src/app"
    command: sh -c "npm run start:dev"
    restart: always

  mysql:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - ${MYSQL_PORT}
    volumes:
      - api-mysql:/var/lib/mysql
    restart: always

volumes:
  api-mysql: