name: paimon CI
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - run: |
          touch .env
          echo "${{ secrets.PAIMON_NESTJS_PROD }}" > .env
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - name: Deploy SSH glubglub
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.TARGET }}
          SCRIPT_BEFORE: ${{ secrets.SCRIPT_BEFORE }}
          SCRIPT_AFTER: ${{ secrets.SCRIPT_AFTER }}
